# Generated by Django 6.0 on 2025-12-17 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=150)),
                ('nombre_comercial', models.CharField(max_length=150)),
                ('ruc_nit', models.CharField(max_length=150)),
                ('pais', models.SmallIntegerField()),
                ('moneda', models.SmallIntegerField()),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('estado', models.SmallIntegerField()),
                ('creada_el', models.DateTimeField()),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='UnidadOrganizacional',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.SmallIntegerField()),
                ('ubicacion', models.CharField(max_length=150)),
                ('estado', models.SmallIntegerField()),
                ('creada_el', models.DateTimeField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
                ('unidad_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unidadorganizacional')),
            ],
            options={
                'db_table': 'unidadorganizacional',
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nivel', models.CharField(max_length=150)),
                ('salario_referencial', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unidadorganizacional')),
            ],
            options={
                'db_table': 'puesto',
            },
        ),
    ]
