# Generated by Django 6.0 on 2025-12-17 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportacionNomina',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=150)),
                ('total_horas', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_extras', models.DecimalField(decimal_places=2, max_digits=7)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('archivo_url', models.TextField()),
                ('generado_el', models.DateTimeField()),
                ('estado', models.SmallIntegerField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
            ],
            options={
                'db_table': 'exportacionnomina',
            },
        ),
        migrations.CreateModel(
            name='IntegracionERP',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('erp_nombre', models.CharField(max_length=150)),
                ('tipo', models.SmallIntegerField()),
                ('metodo', models.SmallIntegerField()),
                ('endpoint', models.CharField(max_length=150)),
                ('credenciales', models.JSONField(blank=True, null=True)),
                ('mapeos', models.JSONField(blank=True, null=True)),
                ('activo', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
            ],
            options={
                'db_table': 'integracionerp',
            },
        ),
        migrations.CreateModel(
            name='ReporteProgramado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.SmallIntegerField()),
                ('parametros', models.JSONField(blank=True, null=True)),
                ('frecuencia_cron', models.CharField(max_length=150)),
                ('formato', models.SmallIntegerField()),
                ('destinatarios', models.JSONField(blank=True, null=True)),
                ('activo', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
            ],
            options={
                'db_table': 'reporteprogramado',
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('evento', models.SmallIntegerField()),
                ('url', models.TextField()),
                ('secreto', models.CharField(max_length=150)),
                ('activo', models.BooleanField()),
                ('reintentos_max', models.IntegerField()),
                ('ultimo_envio_el', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
            ],
            options={
                'db_table': 'webhook',
            },
        ),
    ]
