# Generated by Django 6.0 on 2025-12-17 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('empleados', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoVacaciones',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=150)),
                ('dias_asignados', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dias_tomados', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dias_disponibles', models.DecimalField(decimal_places=2, max_digits=5)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
            ],
            options={
                'db_table': 'saldovacaciones',
            },
        ),
        migrations.CreateModel(
            name='SolicitudAusencia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('dias_habiles', models.IntegerField()),
                ('motivo', models.TextField()),
                ('estado', models.SmallIntegerField()),
                ('flujo_actual', models.IntegerField()),
                ('adjunto_url', models.TextField(blank=True, null=True)),
                ('creada_el', models.DateTimeField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
            ],
            options={
                'db_table': 'solicitudausencia',
            },
        ),
        migrations.CreateModel(
            name='AprobacionAusencia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('accion', models.SmallIntegerField()),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('aprobador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ausencias.solicitudausencia')),
            ],
            options={
                'db_table': 'aprobacionausencia',
            },
        ),
        migrations.CreateModel(
            name='TipoAusencia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('afecta_sueldo', models.BooleanField()),
                ('requiere_soporte', models.BooleanField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
            ],
            options={
                'db_table': 'tipoausencia',
            },
        ),
        migrations.AddField(
            model_name='solicitudausencia',
            name='tipo_ausencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ausencias.tipoausencia'),
        ),
    ]
