# Generated by Django 6.0 on 2025-12-24 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ausencias', '0001_initial'),
        ('core', '0002_alter_puesto_empresa_alter_puesto_unidad_and_more'),
        ('empleados', '0002_alter_contrato_empleado_alter_contrato_empresa_and_more'),
        ('usuarios', '0002_alter_permiso_rol_alter_rol_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprobacionausencia',
            name='aprobador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='aprobacionausencia',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ausencias.solicitudausencia'),
        ),
        migrations.AlterField(
            model_name='saldovacaciones',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='saldovacaciones',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='solicitudausencia',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='solicitudausencia',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='solicitudausencia',
            name='tipo_ausencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ausencias.tipoausencia'),
        ),
        migrations.AlterField(
            model_name='tipoausencia',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
    ]
