# Generated by Django 6.0 on 2025-12-17 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionDesempeno',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=150)),
                ('tipo', models.SmallIntegerField()),
                ('instrumento', models.JSONField(blank=True, null=True)),
                ('puntaje_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comentarios', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_realizadas', to='empleados.empleado')),
            ],
            options={
                'db_table': 'evaluaciondesempeno',
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('unidad', models.SmallIntegerField()),
                ('origen_datos', models.SmallIntegerField()),
                ('formula', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
            ],
            options={
                'db_table': 'kpi',
            },
        ),
        migrations.CreateModel(
            name='PlantillaKPI',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('aplica_a', models.SmallIntegerField()),
                ('objetivos', models.JSONField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
            ],
            options={
                'db_table': 'plantillakpi',
            },
        ),
        migrations.CreateModel(
            name='AsignacionKPI',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('desde', models.DateField()),
                ('hasta', models.DateField(blank=True, null=True)),
                ('ajustes_personalizados', models.JSONField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kpi.plantillakpi')),
            ],
            options={
                'db_table': 'asignacionkpi',
            },
        ),
        migrations.CreateModel(
            name='ResultadoKPI',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cumplimiento_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('clasificacion', models.SmallIntegerField()),
                ('calculado_el', models.DateTimeField()),
                ('fuente', models.CharField(max_length=150)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kpi.kpi')),
            ],
            options={
                'db_table': 'resultadokpi',
            },
        ),
    ]
