# Generated by Django 6.0 on 2025-12-24 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_alter_asignacionturno_empleado_and_more'),
        ('core', '0002_alter_puesto_empresa_alter_puesto_unidad_and_more'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='turno_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistencia.turno'),
        ),
        migrations.AlterField(
            model_name='documentoempleado',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='documentoempleado',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.puesto'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadorganizacional'),
        ),
    ]
