# Generated by Django 6.0 on 2025-12-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionTurno',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('es_rotativo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'asignacionturno',
            },
        ),
        migrations.CreateModel(
            name='DispositivoEmpleado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.SmallIntegerField()),
                ('device_uid', models.CharField(blank=True, max_length=150, null=True)),
                ('ultimo_uso_el', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'dispositivoempleado',
            },
        ),
        migrations.CreateModel(
            name='EventoAsistencia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.SmallIntegerField()),
                ('registrado_el', models.DateTimeField()),
                ('fuente', models.SmallIntegerField()),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dentro_geocerca', models.BooleanField(default=False)),
                ('foto_url', models.TextField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'eventoasistencia',
            },
        ),
        migrations.CreateModel(
            name='GeoCerca',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.SmallIntegerField()),
                ('coordenadas', models.JSONField(blank=True, null=True)),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'geocerca',
            },
        ),
        migrations.CreateModel(
            name='JornadaCalculada',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_primera_entrada', models.DateTimeField()),
                ('hora_ultimo_salida', models.DateTimeField()),
                ('minutos_trabajados', models.IntegerField()),
                ('minutos_tardanza', models.IntegerField()),
                ('minutos_extra', models.IntegerField()),
                ('estado', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'jornadacalculada',
            },
        ),
        migrations.CreateModel(
            name='ReglaAsistencia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('considera_tardanza_desde_min', models.IntegerField()),
                ('calculo_horas_extra', models.SmallIntegerField(default=0)),
                ('ip_permitidas', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reglaasistencia',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('dias_semana', models.JSONField()),
                ('tolerancia_minutos', models.IntegerField()),
                ('requiere_gps', models.BooleanField(default=False)),
                ('requiere_foto', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'turno',
            },
        ),
    ]
