# Generated by Django 6.0 on 2025-12-17 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencia', '0001_initial'),
        ('core', '0001_initial'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionturno',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='asignacionturno',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='dispositivoempleado',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='dispositivoempleado',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='eventoasistencia',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='eventoasistencia',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='geocerca',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='jornadacalculada',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='jornadacalculada',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='reglaasistencia',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='reglaasistencia',
            name='geocerca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='asistencia.geocerca'),
        ),
        migrations.AddField(
            model_name='turno',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='asignacionturno',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asistencia.turno'),
        ),
    ]
