# Generated by Django 6.0 on 2025-12-17 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=150)),
                ('entidad', models.CharField(max_length=150)),
                ('entidad_id', models.BigIntegerField()),
                ('detalles', models.JSONField()),
                ('fecha', models.DateTimeField()),
                ('ip', models.CharField(blank=True, max_length=150, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'logauditoria',
            },
        ),
    ]
