# Generated by Django 6.0 on 2025-12-17 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('canal', models.SmallIntegerField()),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('enviada_el', models.DateTimeField()),
                ('leida_el', models.DateTimeField(blank=True, null=True)),
                ('accion_url', models.CharField(blank=True, max_length=150, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
            ],
            options={
                'db_table': 'notificacion',
            },
        ),
    ]
