# Generated by Django 6.0 on 2025-12-24 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_puesto_empresa_alter_puesto_unidad_and_more'),
        ('empleados', '0002_alter_contrato_empleado_alter_contrato_empresa_and_more'),
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
    ]
