# Generated by Django 6.0 on 2025-12-29 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_permiso_rol_alter_rol_empresa_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuariorol',
            unique_together={('usuario', 'rol')},
        ),
    ]
